const CK="sm_v50_checkins", WK="sm_v50_workouts", PK="sm_v50_program", MK="sm_v50_mode";
const $=id=>document.getElementById(id);
function gc(){return JSON.parse(localStorage.getItem(CK)||"[]")} function sc(v){localStorage.setItem(CK,JSON.stringify(v))}
function gw(){return JSON.parse(localStorage.getItem(WK)||"[]")} function sw(v){localStorage.setItem(WK,JSON.stringify(v))}
function gp(){return localStorage.getItem(PK)||"30 Day Reset"} function sp(v){localStorage.setItem(PK,v)}
function gm(){return localStorage.getItem(MK)||"morning"} function sm(v){localStorage.setItem(MK,v)}
function today(){return new Date().toISOString().slice(0,10)}
function ready(e){if(!e)return 0;const p=Math.min(Number(e.proteinGoal||e.proteinActual||0)/190,1)*20,s=Math.min(Number(e.stepsGoal||e.stepsActual||0)/8000,1)*15,en=(Math.min(Number(e.energy||0),10)/10)*20,sl=(Math.min(Number(e.sleep||0),10)/10)*10,b=((10-Math.min(Number(e.backPain||0),10))/10)*17.5,k=((10-Math.min(Number(e.kneePain||0),10))/10)*17.5,comp=(e.nutritionCompliance==="clean"?10:e.nutritionCompliance==="mostly"?7:e.nutritionCompliance==="off"?3:e.nutritionCompliance==="sugar"?2:e.nutritionCompliance==="alcohol"?1:5);return Math.max(0,Math.round(p+s+en+sl+b+k+comp-15))}
function coach(e,r){if(!e)return"Start with a morning check-in.";if(Number(e.backPain||0)>=6)return"Recovery walk + mobility. Protect the back today.";if(Number(e.kneePain||0)>=6)return"Upper body or recovery day. Keep knee stress down.";if(r>=85)return"Peak day. Push your main lift and finish strong.";if(r>=70)return"Solid day. Hit your full workout and protein target.";if(r>=55)return"Moderate day. Keep momentum without grinding.";return"Reset day. Focus on steps, hydration, protein, and recovery."}
function mission(e,r){if(!e)return{type:"READY",lead:"Complete your check-in to generate your mission.",items:[],reason:"No data yet."};if(Number(e.backPain||0)>=6)return{type:"RECOVERY",lead:"Protect your back and keep momentum.",items:["Walk 10–20 minutes","Do bird dogs + curl-ups","Hit protein goal"],reason:"Back pain is elevated, so intensity should drop."};if(Number(e.kneePain||0)>=6)return{type:"UPPER",lead:"Shift stress off the knee.",items:["Train upper body only","Keep steps easy but steady","No deep squats or step-ups"],reason:"Knee pain is elevated, so lower-body load should be reduced."};if(r>=85)return{type:"ATTACK",lead:"This is a high-readiness day.",items:["Hit your main workout","Push the first compound movement","Finish with your target steps"],reason:"Energy, pain, and momentum support a hard training day."};if(r>=70)return{type:"BUILD",lead:"Good day to move forward.",items:["Complete your planned workout","Hit protein goal","Stay on nutrition plan"],reason:"You are in a solid training window."};if(r>=55)return{type:"MODERATE",lead:"Keep momentum, not ego.",items:["Train with controlled effort","Choose cleaner food today","Get your minimum steps"],reason:"Some variables are off, but progress is still available."};return{type:"RESET",lead:"Win the day with basics.",items:["Recovery walk","Protein first at meals","Early sleep tonight"],reason:"Your recovery inputs suggest a reset day."}}
function streak(arr){if(!arr.length)return 0;const dates=[...new Set(arr.map(x=>x.date))].sort().reverse();let count=0;let d=new Date();while(true){const k=d.toISOString().slice(0,10);if(dates.includes(k)){count++;d.setDate(d.getDate()-1)}else break}return count}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.t).classList.add('active')});
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.m));
document.querySelectorAll('.prog').forEach(b=>b.onclick=()=>{document.querySelectorAll('.prog').forEach(x=>x.classList.remove('active'));b.classList.add('active');sp(b.dataset.p);$('programStatus').textContent=`Active program: ${b.dataset.p}`});
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$(b.dataset.fill).value=b.dataset.value});
function setMode(mode){sm(mode);document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.m===mode));$('modeLabel').textContent=mode.toUpperCase();document.querySelectorAll('.morning').forEach(el=>el.classList.toggle('hidden',mode!=='morning'));document.querySelectorAll('.evening').forEach(el=>el.classList.toggle('hidden',mode!=='evening'))}
function renderHome(){const c=gc(),e=[...c].sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0],r=ready(e),m=mission(e,r);$('momentumScore').textContent=`${r}%`;$('momentumBar').style.width=`${r}%`;$('coachMessage').textContent=coach(e,r);$('statWeight').textContent=e?.weight?`${e.weight} lb`:'--';$('statWaist').textContent=e?.waist?`${e.waist} in`:'--';$('statStreak').textContent=streak(c);$('statWorkouts').textContent=gw().length;$('statProtein').textContent=e?`${e.proteinGoal||'--'} / ${e.proteinActual||'--'}`:'--';$('statSteps').textContent=e?`${e.stepsGoal||'--'} / ${e.stepsActual||'--'}`:'--';$('sumEntries').textContent=c.length;const avg=k=>{const v=c.map(x=>Number(x[k]||0)).filter(n=>n>0);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0};$('sumProtein').textContent=avg('proteinActual')||avg('proteinGoal');$('sumSteps').textContent=avg('stepsActual')||avg('stepsGoal');$('sumWorkouts').textContent=gw().length;$('homeMission').innerHTML=m.items.length?m.items.map(x=>`<div class="missionchip">${x}</div>`).join(''):'<div class="hint">No mission yet.</div>';$('missionType').textContent=m.type;$('missionLead').textContent=m.lead;$('missionList').innerHTML=m.items.length?m.items.map(x=>`<div class="missionchip">${x}</div>`).join(''):'<div class="hint">No mission yet.</div>';$('decisionReason').textContent=m.reason;$('heroProgram')&&($('heroProgram').textContent=gp());drawWeight()}
function drawWeight(){const canvas=$('weightChart'),ctx=canvas.getContext('2d'),data=gc();const w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);const s=[...data].sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(-10),vals=s.map(d=>Number(d.weight||0)).filter(v=>v>0);if(!vals.length){ctx.fillStyle='#94a3b8';ctx.font='14px sans-serif';ctx.fillText('No data yet',16,28);return}const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1);ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<4;i++){const y=20+(h-40)*(i/3);ctx.beginPath();ctx.moveTo(10,y);ctx.lineTo(w-10,y);ctx.stroke()}ctx.strokeStyle='#f59e0b';ctx.lineWidth=3;ctx.beginPath();s.forEach((d,i)=>{const v=Number(d.weight||0),x=16+((w-32)*(s.length===1?0.5:i/(s.length-1))),y=h-18-(((v-min)/range)*(h-40));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke()}
function save(){const x={date:$('date').value||today(),mode:gm(),weight:$('weight').value,waist:$('waist').value,sleep:$('sleep').value,energy:$('energy').value,backPain:$('backPain').value,kneePain:$('kneePain').value,proteinGoal:$('proteinGoal').value,stepsGoal:$('stepsGoal').value,proteinActual:$('proteinActual').value,stepsActual:$('stepsActual').value,workoutDone:$('workoutDone').value,nutritionCompliance:$('nutritionCompliance').value,notes:$('notes').value};const c=gc();c.push(x);sc(c);$('status').textContent=`Saved ${x.date} ${x.mode} check-in.`;renderHome();renderHistory()}
function clearF(){$('date').value=today();['weight','waist','sleep','energy','backPain','kneePain','proteinGoal','stepsGoal','proteinActual','stepsActual','workoutDone','nutritionCompliance','notes'].forEach(id=>$(id).value='');$('status').textContent=''}
function renderTrain(){$('trainList').innerHTML='<div class="card"><div class="title">Founder Edition Note</div><div class="hint">Use this version to validate smart check-ins, missions, and programs. The session engine from v4.5 can be merged back into a later v5.1 cloud build.</div></div>'}
function renderHistory(){const c=[...gc()].reverse();$('checkinHistory').innerHTML=c.length?c.map(x=>`<div class="hist"><div class="row"><div><div class="value">${x.date} · ${x.mode}</div><div class="small">${x.notes||''}</div></div><div class="badge">${ready(x)}%</div></div><div class="small" style="margin-top:8px">Wt ${x.weight||'--'} · Waist ${x.waist||'--'} · Protein ${x.proteinGoal||'--'}/${x.proteinActual||'--'} · Steps ${x.stepsGoal||'--'}/${x.stepsActual||'--'}</div></div>`).join(''):'<div class="small">No check-ins yet.</div>';const h=[...gw()].reverse();$('workoutHistory').innerHTML=h.length?h.map(x=>`<div class="hist"><div class="row"><div><div class="value">${x.name}</div><div class="small">${x.date}</div></div><div class="badge">${x.completed}/${x.total}</div></div><div class="small" style="margin-top:8px">${x.exerciseNames.join(', ')}</div></div>`).join(''):'<div class="small">No completed workouts yet.</div>'}
function exportJ(){const blob=new Blob([JSON.stringify({checkins:gc(),workouts:gw(),program:gp()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='savage_metabo_v50_data.json';a.click();URL.revokeObjectURL(url)}
$('saveBtn').onclick=save;$('clearBtn').onclick=clearF;$('exportBtn').onclick=exportJ;$('date').value=today();setMode(gm());$('programStatus').textContent=`Active program: ${gp()}`;document.querySelectorAll('.prog').forEach(b=>b.classList.toggle('active',b.dataset.p===gp()));renderTrain();renderHome();renderHistory();
